// Minimal, safe wrapper abstraction around libvncserver.
//
// This is intentionally conservative: when the Cargo feature `libvnc` is
// disabled (the default), we provide a safe no-op/stubbed implementation so
// the PoC binary and tests can build and run without the native library.
// When the `libvnc` feature is enabled, this module is the logical place to
// add narrow, unsafe FFI bindings to libvncserver and implement the safe
// wrapper methods there.

#[cfg(not(feature = "libvnc"))]
#[derive(Debug)]
pub struct VncServer {
    /// Optional listening port used by this server (0 if none / not listening)
    port: u16,
}

#[cfg(feature = "libvnc")]
#[derive(Debug)]
pub struct VncServer {
    screen: *mut rfbScreenInfo,
    // pointer to C-allocated framebuffer memory that we own and must free
    framebuffer: *mut ::libc::c_void,
    fb_len: usize,
    width: u32,
    height: u32,
    /// bytes per pixel currently used by the native framebuffer
    bytes_per_pixel: usize,
    /// destination line stride in bytes (per row); 0 if native tightly packed
    dest_stride: usize,
    dest_endianness: Endianness,
    dest_order: ColorOrder,
    /// port this server is (or will be) listening on
    port: u16,
}

/// Byte order / endianness for target framebuffer memory layout.
#[derive(Clone, Copy, Debug)]
pub enum Endianness {
    Little,
    Big,
}

/// Channel order for multi-byte pixels (which channel is stored first).
#[derive(Clone, Copy, Debug)]
pub enum ColorOrder {
    RGB,
    BGR,
    RGBA,
    ARGB,
    BGRA,
    ABGR,
}

#[cfg(feature = "libvnc")]
mod bindings {
    // Generated by bindgen in build.rs (when the 'libvnc' feature is enabled).
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(feature = "libvnc")]
use bindings::*;

impl VncServer {
    /// Initialize a headless VNC server (width x height).
    ///
    /// When the `libvnc` feature is not enabled this returns a stubbed server
    /// object. When `libvnc` is enabled, this method should call the real
    /// libvncserver FFI to create and initialize an rfbScreenInfo object.
    pub fn init_headless(width: u32, height: u32, port: Option<u16>) -> Result<Self, String> {
        // Non-feature stubbed implementation is safe to call anywhere.
        #[cfg(not(feature = "libvnc"))]
        {
            // Simple validation and return a stubbed server value.
            if width == 0 || height == 0 {
                return Err("invalid size".to_owned());
            }
            Ok(VncServer {
                port: port.unwrap_or(0),
            })
        }

        // Feature-enabled path: this is where narrow unsafe FFI would go.
        #[cfg(feature = "libvnc")]
        {
            // NOTE: The actual FFI integration with libvncserver lives here.
            // We'll add very narrow extern declarations so the feature-enabled
            // build can link to the system libvncserver library. For now this
            // is a conservative placeholder that will be fleshed out later.
            if width == 0 || height == 0 {
                return Err("invalid size".to_owned());
            }
            unsafe {
                // pick a port if none provided. To reduce flakiness in tests we
                // attempt to allocate an ephemeral port from the OS and pass it
                // to libvncserver via -rfbport argv option. This is best-effort
                // (small race possible) but prevents hardcoding 5900.
                use std::ffi::CString;
                use std::net::TcpListener;

                let chosen_port: u16 = if let Some(p) = port {
                    p
                } else {
                    // Bind to 127.0.0.1:0 to get an ephemeral port then drop it.
                    match TcpListener::bind("127.0.0.1:0") {
                        Ok(l) => {
                            let p = l
                                .local_addr()
                                .map_err(|e| format!("failed to read ephemeral port: {}", e))?
                                .port();
                            // drop listener to free the port for libvncserver
                            drop(l);
                            p
                        }
                        Err(e) => return Err(format!("failed to allocate ephemeral port: {}", e)),
                    }
                };
                // Prepare minimal argc/argv to satisfy rfbGetScreen signature.
                // Prepare argc/argv with the -rfbport flag so libvncserver uses
                // the chosen port instead of the default 5900.
                let mut argc: libc::c_int = 3;
                // create CStrings which must outlive the call
                let prog = CString::new("x11vnc-rustproof").unwrap();
                let flag = CString::new("-rfbport").unwrap();
                let port_str = CString::new(format!("{}", chosen_port)).unwrap();
                // Build argv pointers vector
                // Keep CString instances alive for the duration of the call and
                // use their pointers (cast to *mut) — we won't take ownership
                // or free them here.
                let mut arg_ptrs: Vec<*mut libc::c_char> = vec![
                    prog.as_ptr() as *mut libc::c_char,
                    flag.as_ptr() as *mut libc::c_char,
                    port_str.as_ptr() as *mut libc::c_char,
                ];
                // libvnc's rfbGetScreen expects a pointer-to-pointer-to-pointer,
                // pass address of our argv pointer reference
                let mut argv: *mut *mut libc::c_char = arg_ptrs.as_mut_ptr();

                let screen = rfbGetScreen(
                    &mut argc as *mut _,
                    &mut (&mut argv) as *mut _,
                    width as libc::c_int,
                    height as libc::c_int,
                    8,
                    3,
                    4,
                );
                if screen.is_null() {
                    return Err("rfbGetScreen returned null".to_owned());
                }
                // Initialize the server — many libvncserver versions return 0 on success
                let rc = rfbInitServer(screen);
                if rc != 0 {
                    // cleanup and return error
                    rfbScreenCleanup(screen);
                    return Err(format!("rfbInitServer failed: {}", rc));
                }
                // determine sizes from the returned rfbScreenInfo (if available)
                let mut width_v: u32 = width;
                let mut height_v: u32 = height;
                // SAFETY: the rfbGetScreen result is assumed valid.
                unsafe {
                    // If bindings expose width/height fields, read them.
                    // Bindgen-generated bindings expose `width` and `height` as c_int.
                    #[allow(unused_unsafe)]
                    {
                        width_v = (*screen).width as u32;
                        height_v = (*screen).height as u32;
                    }
                }
                Ok(VncServer {
                    screen,
                    framebuffer: std::ptr::null_mut(),
                    fb_len: 0,
                    width: width_v,
                    height: height_v,
                    bytes_per_pixel: 0,
                    dest_stride: 0,
                    dest_endianness: Endianness::Little,
                    dest_order: ColorOrder::RGB,
                    port: chosen_port,
                })
            }
        }
    }

    /// Wait for a client to connect or timeout in milliseconds.
    ///
    /// In the stubbed implementation this is a no-op that returns Ok.
    pub fn wait_for_client(&self, _timeout_ms: u32) -> Result<(), String> {
        #[cfg(not(feature = "libvnc"))]
        {
            Ok(())
        }

        #[cfg(feature = "libvnc")]
        {
            // Process libvncserver events until the timeout is reached.
            // This doesn't attempt to be a full client detection routine;
            // it ensures the native event loop is driven for the period
            // requested and provides a simple mechanism to wait for
            // potential incoming clients.
            unsafe {
                let mut remaining = _timeout_ms as i64;
                // We process events in increments (1ms -> 1000 usec) so that
                // we can respond quickly and avoid blocking for a large
                // amount of time.
                while remaining > 0 {
                    // rfbProcessEvents accepts microseconds.
                    let usec = std::cmp::min(1_000, (remaining * 1_000) as i64) as i32;
                    rfbProcessEvents(self.screen, usec as ::libc::c_int);
                    remaining -= (usec as i64) / 1_000;
                }
            }
            Ok(())
        }
    }

    /// Attach a raw framebuffer slice to the running server. In the stubbed
    /// mode this is a no-op; when the `libvnc` feature is enabled we will
    /// attempt to set the server's frameBuffer pointer to the provided slice
    /// memory (unsafe). For now this method is conservative and keeps the
    /// ownership semantics in Rust.
    /// Attach a framebuffer with metadata.
    ///
    /// `stride_bytes` if provided indicates bytes per line in the destination
    /// framebuffer (may be >= width * bytes_per_pixel). `endianness` and
    /// `order` control the target memory layout for multi-byte pixels.
    #[allow(clippy::too_many_arguments)]
    pub fn attach_framebuffer(
        &mut self,
        _buf: &mut [u8],
        _width: u32,
        _height: u32,
        _bpp: u32,
        _stride_bytes: Option<usize>,
        _endianness: Endianness,
        _order: ColorOrder,
    ) -> Result<(), String> {
        #[cfg(not(feature = "libvnc"))]
        {
            // stub: nothing to do
            Ok(())
        }

        #[cfg(feature = "libvnc")]
        {
            // We will allocate a C buffer, copy caller's buffer into it, and
            // set rfbScreenInfo.frameBuffer to point at that C memory. We keep
            // ownership of the C memory on the Rust side and free it at
            // shutdown.
            let bpp_bytes = (_bpp as usize) / 8;
            let expected = (_width as usize)
                .saturating_mul(_height as usize)
                .saturating_mul(bpp_bytes);
            if _buf.len() < expected {
                return Err("source buffer too small".to_string());
            }
            unsafe {
                // allocate C memory
                let ptr = libc::malloc(expected) as *mut ::libc::c_void;
                if ptr.is_null() {
                    return Err("malloc failed".to_string());
                }
                // copy contents
                // If the target framebuffer uses the same bytes-per-pixel as
                // the source we can copy directly; otherwise we copy a
                // converted buffer. The application `Screen` uses RGB24 (3
                // bytes/pixel) so conversion handles that common case.
                if bpp_bytes == 3 {
                    // no conversion required, but copy per-line if stride != width*bpp
                    if let Some(stride) = _stride_bytes {
                        let src_stride = (_width as usize) * 3;
                        for row in 0..(_height as usize) {
                            let src_off = row * src_stride;
                            let dst_off = row * stride;
                            std::ptr::copy_nonoverlapping(
                                _buf.as_ptr().add(src_off),
                                (ptr as *mut u8).add(dst_off),
                                src_stride,
                            );
                        }
                    } else {
                        std::ptr::copy_nonoverlapping(_buf.as_ptr(), ptr as *mut u8, expected);
                    }
                } else if bpp_bytes == 4 {
                    // convert rgb24 -> rgb32 (pad alpha with 0) with chosen ordering/endianness
                    let conv = convert_rgb24_to_bpp_format(
                        _buf,
                        _width as usize,
                        _height as usize,
                        4,
                        _endianness,
                        _order,
                    )
                    .map_err(|e| e)?;
                    if let Some(stride) = _stride_bytes {
                        let dst_stride = stride;
                        let src_stride = (_width as usize) * 4;
                        for row in 0..(_height as usize) {
                            let src_off = row * src_stride;
                            let dst_off = row * dst_stride;
                            std::ptr::copy_nonoverlapping(
                                conv.as_ptr().add(src_off),
                                (ptr as *mut u8).add(dst_off),
                                src_stride,
                            );
                        }
                    } else {
                        std::ptr::copy_nonoverlapping(conv.as_ptr(), ptr as *mut u8, expected);
                    }
                } else {
                    libc::free(ptr);
                    return Err("unsupported bytes_per_pixel".to_string());
                }
                // For 2-byte targets (e.g. RGB565) we'll accept bpp_bytes==2
                if bpp_bytes == 2 {
                    // convert src rgb24 into 16-bit packed values according to requested order/endianness
                    let conv = convert_rgb24_to_bpp_format(
                        _buf,
                        _width as usize,
                        _height as usize,
                        2,
                        _endianness,
                        _order,
                    )
                    .map_err(|e| e)?;
                    if let Some(stride) = _stride_bytes {
                        let dst_stride = stride;
                        let src_stride = (_width as usize) * 2;
                        for row in 0..(_height as usize) {
                            let src_off = row * src_stride;
                            let dst_off = row * dst_stride;
                            std::ptr::copy_nonoverlapping(
                                conv.as_ptr().add(src_off),
                                (ptr as *mut u8).add(dst_off),
                                src_stride,
                            );
                        }
                    } else {
                        std::ptr::copy_nonoverlapping(conv.as_ptr(), ptr as *mut u8, expected);
                    }
                }
                // set into screen struct
                (*self.screen).frameBuffer = ptr as *mut ::libc::c_uchar;
                self.framebuffer = ptr;
                // remember stride / bpp to be used by updates
                self.fb_len = if let Some(s) = _stride_bytes {
                    s * (_height as usize)
                } else {
                    expected
                };
                self.width = _width;
                self.height = _height;
                self.bytes_per_pixel = bpp_bytes;
                self.dest_stride = if let Some(s) = _stride_bytes {
                    s
                } else {
                    (_width as usize) * bpp_bytes
                };
                self.dest_endianness = _endianness;
                self.dest_order = _order;
            }
            Ok(())
        }
    }

    /// Copy updated Rust-managed buffer into the server's C framebuffer and
    /// mark the full screen as modified so clients will be notified.
    #[allow(dead_code)]
    pub fn update_framebuffer(&mut self, _src: &[u8]) -> Result<(), String> {
        #[cfg(not(feature = "libvnc"))]
        {
                Ok(())
        }

        #[cfg(feature = "libvnc")]
        {
            let expected_src = (self.width as usize)
                .saturating_mul(self.height as usize)
                .saturating_mul(3);
            if _src.len() < expected_src {
                return Err("source buffer too small".to_string());
            }
            let expected = (self.width as usize)
                .saturating_mul(self.height as usize)
                .saturating_mul(self.bytes_per_pixel);
            unsafe {
                if self.framebuffer.is_null() {
                    return Err("no framebuffer attached".to_string());
                }
                if self.bytes_per_pixel == 3 {
                    // direct copy but respect stride if the native buffer has a larger stride
                    let dst_stride = (self.width as usize) * self.bytes_per_pixel;
                    if self.fb_len / (self.height as usize) != dst_stride {
                        // destination line stride differs: copy per-line
                        let dest_stride = self.fb_len / (self.height as usize);
                        let src_stride = (self.width as usize) * 3;
                        for row in 0..(self.height as usize) {
                            let src_off = row * src_stride;
                            let dst_off = row * dest_stride;
                            std::ptr::copy_nonoverlapping(
                                _src.as_ptr().add(src_off),
                                (self.framebuffer as *mut u8).add(dst_off),
                                src_stride,
                            );
                        }
                    } else {
                        std::ptr::copy_nonoverlapping(
                            _src.as_ptr(),
                            self.framebuffer as *mut u8,
                            expected,
                        );
                    }
                } else if self.bytes_per_pixel == 4 {
                    let conv = convert_rgb24_to_bpp_format(
                        _src,
                        self.width as usize,
                        self.height as usize,
                        4,
                        self.dest_endianness,
                        self.dest_order,
                    )
                    .map_err(|e| e)?;
                    let dest_stride = self.fb_len / (self.height as usize);
                    let src_stride = (self.width as usize) * 4;
                    if dest_stride != src_stride {
                        for row in 0..(self.height as usize) {
                            let src_off = row * src_stride;
                            let dst_off = row * dest_stride;
                            std::ptr::copy_nonoverlapping(
                                conv.as_ptr().add(src_off),
                                (self.framebuffer as *mut u8).add(dst_off),
                                src_stride,
                            );
                        }
                    } else {
                        std::ptr::copy_nonoverlapping(
                            conv.as_ptr(),
                            self.framebuffer as *mut u8,
                            expected,
                        );
                    }
                } else if self.bytes_per_pixel == 2 {
                    let conv = convert_rgb24_to_bpp_format(
                        _src,
                        self.width as usize,
                        self.height as usize,
                        2,
                        self.dest_endianness,
                        self.dest_order,
                    )
                    .map_err(|e| e)?;
                    let dest_stride = self.fb_len / (self.height as usize);
                    let src_stride = (self.width as usize) * 2;
                    if dest_stride != src_stride {
                        for row in 0..(self.height as usize) {
                            let src_off = row * src_stride;
                            let dst_off = row * dest_stride;
                            std::ptr::copy_nonoverlapping(
                                conv.as_ptr().add(src_off),
                                (self.framebuffer as *mut u8).add(dst_off),
                                src_stride,
                            );
                        }
                    } else {
                        std::ptr::copy_nonoverlapping(
                            conv.as_ptr(),
                            self.framebuffer as *mut u8,
                            expected,
                        );
                    }
                } else {
                    return Err("unsupported bytes_per_pixel".to_string());
                }
                // mark entire screen as modified
                rfbMarkRectAsModified(
                    self.screen,
                    0,
                    0,
                    self.width as ::libc::c_int,
                    self.height as ::libc::c_int,
                );
            }
            Ok(())
        }
    }

    /// Update only a rectangle portion of the framebuffer.
    pub fn update_framebuffer_rect(
        &mut self,
        _src: &[u8],
        _x: usize,
        _y: usize,
        _w: usize,
        _h: usize,
    ) -> Result<(), String> {
        #[cfg(not(feature = "libvnc"))]
        {
            Ok(())
        }
        #[cfg(feature = "libvnc")]
        {
            // basic input validation
            if _src.is_empty() { return Err("empty source".to_string()); }
            if _x + _w > (self.width as usize) || _y + _h > (self.height as usize) {
                return Err("rect out of bounds".to_string());
            }
            let src_expected = _w * _h * 3;
            if _src.len() < src_expected {
                return Err("source buffer too small".into());
            }
            unsafe {
                if self.framebuffer.is_null() {
                    return Err("no framebuffer attached".into());
                }
                // For simplicity we convert per-pixel into destination bytes per pixel
                // and copy per-row respecting destination stride.
                let dst_stride = self.dest_stride;
                let dst_bpp = self.bytes_per_pixel;
                for row in 0.._h {
                    let src_off = (row * _w * 3) as usize;
                    let dst_row = _y + row;
                    let dst_off = dst_row * dst_stride + _x * dst_bpp;
                    if dst_bpp == 3 {
                        std::ptr::copy_nonoverlapping(
                            _src.as_ptr().add(src_off),
                            (self.framebuffer as *mut u8).add(dst_off),
                            _w * 3,
                        );
                    } else if dst_bpp == 4 {
                        // convert each pixel from RGB -> 4 bytes target
                        for col in 0.._w {
                            let sidx = src_off + col * 3;
                            let didx = dst_off + col * 4;
                            let r = *_src.get(sidx).unwrap();
                            let g = *_src.get(sidx + 1).unwrap();
                            let b = *_src.get(sidx + 2).unwrap();
                            // put r,g,b,0
                            *(self.framebuffer as *mut u8).add(didx) = r;
                            *(self.framebuffer as *mut u8).add(didx + 1) = g;
                            *(self.framebuffer as *mut u8).add(didx + 2) = b;
                            *(self.framebuffer as *mut u8).add(didx + 3) = 0;
                        }
                    } else if dst_bpp == 2 {
                        // convert to RGB565/555 using existing helpers
                        let conv = convert_rgb24_to_bpp_format(
                            _src,
                            _w,
                            _h,
                            2,
                            self.dest_endianness,
                            self.dest_order,
                        )
                        .map_err(|e| e)?;
                        std::ptr::copy_nonoverlapping(
                            conv.as_ptr(),
                            (self.framebuffer as *mut u8).add(dst_off),
                            _w * 2,
                        );
                    } else {
                        return Err("unsupported bytes_per_pixel".to_string());
                    }
                }
                rfbMarkRectAsModified(
                    self.screen,
                    _x as ::libc::c_int,
                    _y as ::libc::c_int,
                    _w as ::libc::c_int,
                    _h as ::libc::c_int,
                );
            }
            Ok(())
        }
    }

    /// Shutdown and cleanup the server resources. Safe wrapper for cleanup.
    pub fn shutdown(self) {
        #[cfg(not(feature = "libvnc"))]
        {
            // no-op stub
        }

        #[cfg(feature = "libvnc")]
        {
            unsafe {
                if !self.screen.is_null() {
                    // free C-allocated framebuffer first
                    if !self.framebuffer.is_null() {
                        libc::free(self.framebuffer);
                    }
                    rfbScreenCleanup(self.screen);
                }
            }
        }
    }

    /// Return the port that this server will listen on (0 if none / stubbed)
    pub fn listen_port(&self) -> u16 {
        #[cfg(not(feature = "libvnc"))]
        {
            self.port
        }
        #[cfg(feature = "libvnc")]
        {
            self.port
        }
    }
}

/// Convert an RGB24 source buffer (3 bytes per pixel) into a target bytes-per-pixel
/// representation (3 or 4). Returns a Vec<u8> with the converted pixel bytes.
#[allow(dead_code)]
fn convert_rgb24_to_bpp(
    src: &[u8],
    width: usize,
    height: usize,
    dst_bpp: usize,
) -> Result<Vec<u8>, String> {
    if width == 0 || height == 0 {
        return Err("invalid dims".to_string());
    }
    let npix = width.saturating_mul(height);
    let expected = npix.saturating_mul(3);
    if src.len() < expected {
        return Err("source buffer too small".to_string());
    }
    // Delegate to the format-aware converter with default little/RGB semantics
    convert_rgb24_to_bpp_format(
        src,
        width,
        height,
        dst_bpp,
        Endianness::Little,
        ColorOrder::RGB,
    )
}

/// Convert RGB24 into a target format with explicit endianness and color order
#[allow(dead_code)]
fn convert_rgb24_to_bpp_format(
    src: &[u8],
    width: usize,
    height: usize,
    dst_bpp: usize,
    endian: Endianness,
    order: ColorOrder,
) -> Result<Vec<u8>, String> {
    if width == 0 || height == 0 {
        return Err("invalid dims".to_string());
    }
    let npix = width.saturating_mul(height);
    let expected = npix.saturating_mul(3);
    if src.len() < expected {
        return Err("source buffer too small".to_string());
    }

    match dst_bpp {
        3 => Ok(src[..expected].to_vec()),
        4 => {
            let mut out = Vec::with_capacity(npix * 4);
            for i in 0..npix {
                let si = i * 3;
                let r = src[si];
                let g = src[si + 1];
                let b = src[si + 2];

                // Create 4-byte pixel based on requested ordering. We keep the
                // alpha field as 0 for conversions from 24-bit source.
                let mut bytes = match order {
                    ColorOrder::RGB => vec![r, g, b, 0u8],  // R G B A(0)
                    ColorOrder::BGR => vec![b, g, r, 0u8],  // B G R A(0)
                    ColorOrder::RGBA => vec![r, g, b, 0u8], // R G B A
                    ColorOrder::ARGB => vec![0u8, r, g, b], // A R G B
                    ColorOrder::BGRA => vec![b, g, r, 0u8], // B G R A
                    ColorOrder::ABGR => vec![0u8, b, g, r], // A B G R
                };

                // Big-endian target frameworks commonly store bytes with the
                // most-significant byte first. We interpret the ordering above
                // as logical byte order then reverse for big-endian targets so
                // memory layout matches expected endianness.
                if let Endianness::Big = endian {
                    bytes.reverse();
                }

                out.extend_from_slice(&bytes);
            }
            Ok(out)
        }
        15 => {
            // 15-bit RGB (5-5-5) - pack into two bytes: [MSB, LSB] depending on endianness
            // Per-pixel value: r5 (bits 10..14), g5 (bits 5..9), b5 (bits 0..4)
            let mut out = Vec::with_capacity(npix * 2);
            for i in 0..npix {
                let si = i * 3;
                let r = src[si] as u16;
                let g = src[si + 1] as u16;
                let b = src[si + 2] as u16;
                let r5 = (r >> 3) & 0x1F;
                let g5 = (g >> 3) & 0x1F;
                let b5 = (b >> 3) & 0x1F;
                let packed = match order {
                    ColorOrder::RGB | ColorOrder::RGBA | ColorOrder::ARGB => {
                        (r5 << 10) | (g5 << 5) | b5
                    }
                    ColorOrder::BGR | ColorOrder::BGRA | ColorOrder::ABGR => {
                        (b5 << 10) | (g5 << 5) | r5
                    }
                };
                let bytes = match endian {
                    Endianness::Little => packed.to_le_bytes(),
                    Endianness::Big => packed.to_be_bytes(),
                };
                out.push(bytes[0]);
                out.push(bytes[1]);
            }
            Ok(out)
        }
        2 => {
            let mut out = Vec::with_capacity(npix * 2);
            for i in 0..npix {
                let si = i * 3;
                let r = src[si] as u16;
                let g = src[si + 1] as u16;
                let b = src[si + 2] as u16;
                let r5 = (r >> 3) & 0x1F;
                let g6 = (g >> 2) & 0x3F;
                let b5 = (b >> 3) & 0x1F;
                let packed = match order {
                    ColorOrder::RGB | ColorOrder::RGBA | ColorOrder::ARGB => {
                        (r5 << 11) | (g6 << 5) | b5
                    }
                    ColorOrder::BGR | ColorOrder::BGRA | ColorOrder::ABGR => {
                        (b5 << 11) | (g6 << 5) | r5
                    }
                };
                let bytes = match endian {
                    Endianness::Little => packed.to_le_bytes(),
                    Endianness::Big => packed.to_be_bytes(),
                };
                out.push(bytes[0]);
                out.push(bytes[1]);
            }
            Ok(out)
        }
        _ => Err("unsupported dst_bpp".to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn init_headless_works() {
        let s = VncServer::init_headless(800, 600, None);
        assert!(s.is_ok());
    }

    #[test]
    fn wait_for_client_is_ok() {
        let s = VncServer::init_headless(200, 150, None).unwrap();
        assert!(s.wait_for_client(1000).is_ok());
    }

    #[test]
    fn wait_for_client_zero_ms_ok() {
        let s = VncServer::init_headless(200, 150, None).unwrap();
        assert!(s.wait_for_client(0).is_ok());
    }

    #[test]
    fn attach_framebuffer_stub_ok() {
        let mut s = VncServer::init_headless(200, 150, None).unwrap();
        let mut buf = vec![0u8; (200 * 150 * 3) as usize];
        assert!(s
            .attach_framebuffer(
                &mut buf,
                200,
                150,
                24,
                None,
                Endianness::Little,
                ColorOrder::RGB
            )
            .is_ok());
    }

    #[test]
    fn update_framebuffer_rect_stub_ok() {
        let mut s = VncServer::init_headless(20, 10, None).unwrap();
        // attach a 20x10 screen as our source
        let mut buf = vec![0u8; 20 * 10 * 3];
        assert!(s
            .attach_framebuffer(&mut buf, 20, 10, 24, None, Endianness::Little, ColorOrder::RGB)
            .is_ok());
        // update a 4x4 rect at 2,2
        let rect = vec![0x11u8; 4 * 4 * 3];
        assert!(s.update_framebuffer_rect(&rect, 2, 2, 4, 4).is_ok());
    }

    #[test]
    fn init_headless_with_explicit_port() {
        // Confirm that passing an explicit port is accepted and stored
        let port: u16 = 5905;
        let s = VncServer::init_headless(64, 48, Some(port)).expect("init_headless failed");
        assert_eq!(s.listen_port(), port);
    }

    #[test]
    fn convert_rgb24_to_bpp_4bytes() {
        // create a 2x1 image (2 pixels)
        let src = vec![0x11u8, 0x22u8, 0x33u8, 0x44u8, 0x55u8, 0x66u8];
        let out = super::convert_rgb24_to_bpp(&src, 2, 1, 4).expect("conv");
        assert_eq!(out.len(), 8);
        // first pixel
        assert_eq!(&out[0..4], &[0x11, 0x22, 0x33, 0x00]);
        // second pixel
        assert_eq!(&out[4..8], &[0x44, 0x55, 0x66, 0x00]);
    }

    #[test]
    fn convert_rgb24_to_bpp_3bytes() {
        let src = vec![1u8, 2u8, 3u8, 4u8, 5u8, 6u8];
        let out = super::convert_rgb24_to_bpp(&src, 2, 1, 3).expect("conv");
        assert_eq!(out, src);
    }

    #[test]
    fn convert_rgb24_to_rgb565_little_rgb() {
        // two pixels: red and blue
        let src = vec![255u8, 0, 0, 0, 0, 255u8];
        let out =
            super::convert_rgb24_to_bpp_format(&src, 2, 1, 2, Endianness::Little, ColorOrder::RGB)
                .unwrap();
        // red -> 0xF800 -> little [0x00, 0xF8]
        assert_eq!(&out[0..2], &[0x00, 0xF8]);
        // blue -> 0x001F -> little [0x1F, 0x00]
        assert_eq!(&out[2..4], &[0x1F, 0x00]);
    }

    #[test]
    fn convert_rgb24_to_rgb565_big_bgr() {
        // two pixels: red and blue
        let src = vec![255u8, 0, 0, 0, 0, 255u8];
        // big-endian + BGR
        let out =
            super::convert_rgb24_to_bpp_format(&src, 2, 1, 2, Endianness::Big, ColorOrder::BGR)
                .unwrap();
        // For BGR order red (255,0,0) maps to low bits (r5 at LSB), result = 0x001F -> BE [0x00,0x1F]
        assert_eq!(&out[0..2], &[0x00, 0x1F]);
        // For blue (0,0,255) with BGR -> high bits (b5 << 11) => 0xF800 -> BE [0xF8, 0x00]
        assert_eq!(&out[2..4], &[0xF8, 0x00]);
    }

    #[test]
    fn convert_rgb24_format_big_endian_bgr() {
        // src two pixels: [R,G,B] pairs
        let src = vec![0x01u8, 0x02u8, 0x03u8, 0x11u8, 0x12u8, 0x13u8];
        // Order BGR, Big-endian: per-pixel bytes are reversed after reordering -> [0, R, G, B] reversed -> [B,G,R,0]
        let out =
            super::convert_rgb24_to_bpp_format(&src, 2, 1, 4, Endianness::Big, ColorOrder::BGR)
                .unwrap();
        assert_eq!(out.len(), 8);
        // first pixel: bytes reversed of [B,G,R,0] -> [0,R,G,B]? Wait, our function reverses bytes for big endian, so initial bytes are [B,G,R,0] then reversed => [0,R,G,B]
        // So for src pixel (0x01,0x02,0x03) with BGR initial -> [0x03,0x02,0x01,0x00], reversed -> [0x00,0x01,0x02,0x03]
        assert_eq!(&out[0..4], &[0x00, 0x01, 0x02, 0x03]);
        // second pixel
        assert_eq!(&out[4..8], &[0x00, 0x11, 0x12, 0x13]);
    }

    #[test]
    fn convert_rgb24_to_rgb555_little_rgb() {
        // two pixels: red and blue
        let src = vec![255u8, 0, 0, 0, 0, 255u8];
        let out =
            super::convert_rgb24_to_bpp_format(&src, 2, 1, 15, Endianness::Little, ColorOrder::RGB)
                .unwrap();
        // red -> 0x7C00 -> little [0x00, 0x7C]
        assert_eq!(&out[0..2], &[0x00, 0x7C]);
        // blue -> 0x001F -> little [0x1F, 0x00]
        assert_eq!(&out[2..4], &[0x1F, 0x00]);
    }

    #[test]
    fn convert_rgb24_to_rgb555_big_bgr() {
        // two pixels: red and blue
        let src = vec![255u8, 0, 0, 0, 0, 255u8];
        // big-endian + BGR
        let out =
            super::convert_rgb24_to_bpp_format(&src, 2, 1, 15, Endianness::Big, ColorOrder::BGR)
                .unwrap();
        // red -> BGR mapping puts r in LSB -> 0x001F -> BE [0x00,0x1F]
        assert_eq!(&out[0..2], &[0x00, 0x1F]);
        // blue -> BGR mapping yields 0x7C00 -> BE [0x7C, 0x00]
        assert_eq!(&out[2..4], &[0x7C, 0x00]);
    }

    #[test]
    fn convert_rgb24_to_bpp_argb_little() {
        // one pixel to check ARGB ordering little-endian
        let src = vec![0x01u8, 0x02u8, 0x03u8];
        let out =
            super::convert_rgb24_to_bpp_format(&src, 1, 1, 4, Endianness::Little, ColorOrder::ARGB)
                .unwrap();
        // ARGB little-endian layout should be [A,R,G,B] => A is 0
        assert_eq!(&out[0..4], &[0x00, 0x01, 0x02, 0x03]);
    }
}
